
const ActionTypes = {

  LOGIN_REQUEST : 'LOGIN_REQUEST',
  LOGIN_SUCCESS : 'LOGIN_SUCCESS',
  LOGIN_ERROR   : 'LOGIN_ERROR',

  PASSWORD_RESET_REQUEST  : 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_SUCCESS  : 'PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_ERROR    : 'PASSWORD_RESET_ERROR',

  FETCH_USERINFO_REQUEST : 'FETCH_USERINFO_REQUEST',
  FETCH_USERINFO_SUCCESS : 'FETCH_USERINFO_SUCCESS',
  FETCH_USERINFO_ERROR   : 'FETCH_USERINFO_ERROR',

  SEARCH_ARTICLES_REQUEST : 'SEARCH_ARTICLES_REQUEST',
  SEARCH_ARTICLES_SUCCESS : 'SEARCH_ARTICLES_SUCCESS',
  SEARCH_ARTICLES_ERROR   : 'SEARCH_ARTICLES_ERROR',

  FETCH_FILTER_OPTIONS_REQUEST : 'FETCH_FILTER_OPTIONS_REQUEST',
  FETCH_FILTER_OPTIONS_SUCCESS : 'FETCH_FILTER_OPTIONS_SUCCESS',
  FETCH_FILTER_OPTIONS_ERROR   : 'FETCH_FILTER_OPTIONS_ERROR',

  FETCH_COLLECTION_ARTICLES_REQUEST : 'FETCH_COLLECTION_ARTICLES_REQUEST',
  FETCH_COLLECTION_ARTICLES_SUCCESS : 'FETCH_COLLECTION_ARTICLES_SUCCESS',
  FETCH_COLLECTION_ARTICLES_ERROR   : 'FETCH_COLLECTION_ARTICLES_ERROR',

  FIND_ARTICLE_REQUEST : 'FIND_ARTICLE_REQUEST',
  FIND_ARTICLE_SUCCESS : 'FIND_ARTICLE_SUCCESS',
  FIND_ARTICLE_ERROR   : 'FIND_ARTICLE_ERROR',


  PAGINATION_FIRST_PAGE       : 'PAGINATION_FIRST_PAGE',
  PAGINATION_PREVIOUS_PAGE    : 'PAGINATION_PREVIOUS_PAGE',
  PAGINATION_NEXT_PAGE        : 'PAGINATION_NEXT_PAGE',
  PAGINATION_LAST_PAGE        : 'PAGINATION_LAST_PAGE',
  PAGINATION_CHANGE_PAGE_SIZE : 'PAGINATION_CHANGE_PAGE_SIZE',

  SELECT_ITEM               : 'SELECT_ITEM',
  DESELECT_ITEM             : 'DESELECT_ITEM',
  SELECT_ALL                : 'SELECT_ALL',
  DESELECT_ALL              : 'DESELECT_ALL',

  CREATE_COLLECTION_REQUEST : 'CREATE_COLLECTION_REQUEST',
  CREATE_COLLECTION_SUCCESS : 'CREATE_COLLECTION_SUCCESS',
  CREATE_COLLECTION_ERROR   : 'CREATE_COLLECTION_ERROR',

  UPDATE_COLLECTION_REQUEST : 'UPDATE_COLLECTION_REQUEST',
  UPDATE_COLLECTION_SUCCESS : 'UPDATE_COLLECTION_SUCCESS',
  UPDATE_COLLECTION_ERROR   : 'UPDATE_COLLECTION_ERROR',

  DELETE_COLLECTION_REQUEST : 'DELETE_COLLECTION_REQUEST',
  DELETE_COLLECTION_SUCCESS : 'DELETE_COLLECTION_SUCCESS',
  DELETE_COLLECTION_ERROR   : 'DELETE_COLLECTION_ERROR',

  ADD_TO_COLLECTION_REQUEST : 'ADD_TO_COLLECTION_REQUEST',
  ADD_TO_COLLECTION_SUCCESS : 'ADD_TO_COLLECTION_SUCCESS',
  ADD_TO_COLLECTION_ERROR   : 'ADD_TO_COLLECTION_ERROR',

  REMOVE_FROM_COLLECTION_REQUEST : 'REMOVE_FROM_COLLECTION_REQUEST',
  REMOVE_FROM_COLLECTION_SUCCESS : 'REMOVE_FROM_COLLECTION_SUCCESS',
  REMOVE_FROM_COLLECTION_ERROR   : 'REMOVE_FROM_COLLECTION_ERROR',

  ADD_SELECTED_ARTICLES_TO_EXISTING_COLLECTION: 'ADD_SELECTED_ARTICLES_TO_EXISTING_COLLECTION',
  ADD_SELECTED_ARTICLES_TO_NEW_COLLECTION     : 'ADD_SELECTED_ARTICLES_TO_NEW_COLLECTION',
  EDIT_COLLECTION_DETAILS : 'EDIT_COLLECTION_DETAILS',


  EXPORT_SELECTED_ARTICLES  : 'EXPORT_SELECTED_ARTICLES',
  EXPORT_ALL_ARTICLES       : 'EXPORT_ALL_ARTICLES',
  EXPORT_SINGLE_ARTICLE     : 'EXPORT_SINGLE_ARTICLE',

  PREPARE_EXPORT_REQUEST    : 'PREPARE_EXPORT_REQUEST',
  PREPARE_EXPORT_SUCCESS    : 'PREPARE_EXPORT_SUCCESS',
  PREPARE_EXPORT_ERROR      : 'PREPARE_EXPORT_ERROR',

  FETCH_PROJECTS_REQUEST : 'FETCH_PROJECTS_REQUEST',
  FETCH_PROJECTS_SUCCESS : 'FETCH_PROJECTS_SUCCESS',
  FETCH_PROJECTS_ERROR   : 'FETCH_PROJECTS_ERROR',

  FETCH_ORGANIZATIONS_REQUEST : 'FETCH_ORGANIZATIONS_REQUEST',
  FETCH_ORGANIZATIONS_SUCCESS : 'FETCH_ORGANIZATIONS_SUCCESS',
  FETCH_ORGANIZATIONS_ERROR   : 'FETCH_ORGANIZATIONS_ERROR',

  FETCH_OVERVIEW_REQUEST: 'FETCH_OVERVIEW_REQUEST',
  FETCH_OVERVIEW_SUCCESS: 'FETCH_OVERVIEW_SUCCESS',
  FETCH_OVERVIEW_ERROR: 'FETCH_OVERVIEW_ERROR',

  UPDATE_PROFILE_REQUEST          : 'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS          : 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_ERROR            : 'UPDATE_PROFILE_ERROR',

  CHANGE_PASSWORD_REQUEST         : 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS         : 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_ERROR           : 'CHANGE_PASSWORD_ERROR',

  FETCH_DIGESTS_REQUEST          : 'FETCH_DIGESTS_REQUEST',
  FETCH_DIGESTS_SUCCESS          : 'FETCH_DIGESTS_SUCCESS',
  FETCH_DIGESTS_ERROR            : 'FETCH_DIGESTS_ERROR',

  UPDATE_DIGESTS_REQUEST          : 'UPDATE_DIGESTS_REQUEST',
  UPDATE_DIGESTS_SUCCESS          : 'UPDATE_DIGESTS_SUCCESS',
  UPDATE_DIGESTS_ERROR            : 'UPDATE_DIGESTS_ERROR',


  FETCH_TAGS_CHART_REQUEST      : 'FETCH_TAGS_CHART_REQUEST',
  FETCH_TAGS_CHART_SUCCESS      : 'FETCH_TAGS_CHART_SUCCESS',
  FETCH_TAGS_CHART_ERROR        : 'FETCH_TAGS_CHART_ERROR',

  FETCH_AVE_CHART_REQUEST      : 'FETCH_AVE_CHART_REQUEST',
  FETCH_AVE_CHART_SUCCESS      : 'FETCH_AVE_CHART_SUCCESS',
  FETCH_AVE_CHART_ERROR        : 'FETCH_AVE_CHART_ERROR',

  FETCH_IMPRESSIONS_CHART_REQUEST      : 'FETCH_IMPRESSIONS_CHART_REQUEST',
  FETCH_IMPRESSIONS_CHART_SUCCESS      : 'FETCH_IMPRESSIONS_CHART_SUCCESS',
  FETCH_IMPRESSIONS_CHART_ERROR        : 'FETCH_IMPRESSIONS_CHART_ERROR',

  FETCH_LANGUAGES_CHART_REQUEST      : 'FETCH_LANGUAGES_CHART_REQUEST',
  FETCH_LANGUAGES_CHART_SUCCESS      : 'FETCH_LANGUAGES_CHART_SUCCESS',
  FETCH_LANGUAGES_CHART_ERROR        : 'FETCH_LANGUAGES_CHART_ERROR',

  FETCH_MEDIA_TYPES_CHART_REQUEST      : 'FETCH_MEDIA_TYPES_CHART_REQUEST',
  FETCH_MEDIA_TYPES_CHART_SUCCESS      : 'FETCH_MEDIA_TYPES_CHART_SUCCESS',
  FETCH_MEDIA_TYPES_CHART_ERROR        : 'FETCH_MEDIA_TYPES_CHART_ERROR',

  FETCH_OUTLETS_CHART_REQUEST      : 'FETCH_OUTLETS_CHART_REQUEST',
  FETCH_OUTLETS_CHART_SUCCESS      : 'FETCH_OUTLETS_CHART_SUCCESS',
  FETCH_OUTLETS_CHART_ERROR        : 'FETCH_OUTLETS_CHART_ERROR',

  FETCH_REGIONAL_ENGAGEMENT_CHART_REQUEST      : 'FETCH_REGIONAL_ENGAGEMENT_CHART_REQUEST',
  FETCH_REGIONAL_ENGAGEMENT_CHART_SUCCESS      : 'FETCH_REGIONAL_ENGAGEMENT_CHART_SUCCESS',
  FETCH_REGIONAL_ENGAGEMENT_CHART_ERROR        : 'FETCH_REGIONAL_ENGAGEMENT_CHART_ERROR',

  FETCH_REGIONAL_SENTIMENT_CHART_REQUEST      : 'FETCH_REGIONAL_SENTIMENT_CHART_REQUEST',
  FETCH_REGIONAL_SENTIMENT_CHART_SUCCESS      : 'FETCH_REGIONAL_SENTIMENT_CHART_SUCCESS',
  FETCH_REGIONAL_SENTIMENT_CHART_ERROR        : 'FETCH_REGIONAL_SENTIMENT_CHART_ERROR',

  FETCH_TAGS_CHART_REQUEST      : 'FETCH_TAGS_CHART_REQUEST',
  FETCH_TAGS_CHART_SUCCESS      : 'FETCH_TAGS_CHART_SUCCESS',
  FETCH_TAGS_CHART_ERROR        : 'FETCH_TAGS_CHART_ERROR',

  FETCH_EXPERTS_REQUEST : 'FETCH_EXPERTS_REQUEST',
  FETCH_EXPERTS_SUCCESS : 'FETCH_EXPERTS_SUCCESS',
  FETCH_EXPERTS_ERROR : 'FETCH_EXPERTS_ERROR'




};

export default ActionTypes;
